# Generated by Django 5.0.4 on 2024-05-03 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batch', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='status',
            field=models.TextField(default='Confirmation'),
        ),
    ]
