# Generated by Django 5.0.4 on 2024-05-06 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batch', '0004_alter_batch_adress'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='date_confirmed',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='batch',
            name='date_created',
            field=models.DateField(auto_now=True),
        ),
    ]
