# Generated by Django 5.0.4 on 2024-05-07 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batch', '0006_alter_batch_date_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='total',
            field=models.IntegerField(default=0),
        ),
    ]
