# Generated by Django 5.0.4 on 2024-05-07 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batch', '0013_batch_flavour'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='flavour',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
    ]
