# Generated by Django 5.0.4 on 2024-05-07 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batch', '0017_alter_batch_boxes_alter_batch_units_per_box'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='flavour',
            field=models.CharField(choices=[('strawberry', 'Strawberry'), ('blueberry', 'Blueberry')], default='None', max_length=80),
        ),
    ]
