# Generated by Django 5.0.4 on 2024-05-07 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batch', '0007_batch_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='flavour',
            field=models.CharField(choices=[('strawberry', 'Strawberry'), ('bluberry', 'Blueberry')], default=None, max_length=50),
        ),
    ]
