# Generated by Django 5.0.4 on 2024-05-07 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batch', '0012_remove_batch_flavour'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='flavour',
            field=models.CharField(blank=True, choices=[('strawberry', 'Strawberry'), ('bluberry', 'Blueberry')], default='None', max_length=50, null=True),
        ),
    ]
