# Generated by Django 5.0.4 on 2024-05-05 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batch', '0003_batch_adress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='adress',
            field=models.CharField(default='None', max_length=80),
        ),
    ]
