# Generated by Django 5.0.4 on 2024-05-07 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batch', '0005_batch_date_confirmed_batch_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='date_created',
            field=models.DateField(auto_now_add=True),
        ),
    ]
