# Generated by Django 5.0.4 on 2024-05-07 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('batch', '0011_alter_batch_flavour'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='batch',
            name='flavour',
        ),
    ]
